-- FIMBA 2026 (edición 1 / gira 12): check-in/out fecha → eventos.
--
-- Contexto:
--   OFRN asocia check-in/out vía giras_logistica_reglas.id_evento_checkin|checkout
--   a tipos_evento 22 (Check-in) / 23 (Check-Out).
--   FIMBA guardaba solo fechas en fimba_propuestas / fimba_participantes
--   (checkin_at / checkout_at). Esta migración agrega las mismas FKs y crea
--   eventos canónicos:
--     Check-in  → 14:00
--     Check-out → 10:00
--   audiencia_ofrn = none (no confundir con logística Orquesta a las 12:00).
--
-- Idempotente: find-or-create por (id_gira, tipo, fecha, hora).
-- Preferir aplicar la migración:
--   npx supabase db push
-- o re-ejecutar solo el bloque DO de
--   supabase/migrations/20260902122628_fimba_checkin_checkout_eventos.sql
--
-- Verificación:
--   SELECT p.id, p.nombre, p.checkin_at, p.id_evento_checkin, p.checkout_at, p.id_evento_checkout
--   FROM fimba_propuestas p WHERE p.id_edicion = 1 ORDER BY p.nombre;
--
--   SELECT e.id, e.fecha, e.hora_inicio, e.id_tipo_evento, e.descripcion
--   FROM eventos e
--   WHERE e.id_gira = 12 AND e.id_tipo_evento IN (22,23)
--     AND e.hora_inicio IN (TIME '14:00', TIME '10:00')
--     AND COALESCE(e.is_deleted,false)=false
--   ORDER BY e.fecha, e.id_tipo_evento;

-- (Sin SQL ejecutable aquí: el backfill vive en la migración.)
-- Verificación post-migración (edición 1 / gira 12):
-- Eventos canónicos creados (IDs al aplicar 20260902122628):
--   IN 14:00 → 4304(12), 4305(13), 4306(15), 4307(16), 4308(17), 4309(18), 4310(19), 4311(20)
--   OUT 10:00 → 4312(17), 4313(18), 4314(20), 4315(21)
-- Filas: 16 propuestas × in/out + 4 participantes override (Ruggiero cuarteto).

SELECT 1 AS fimba_checkin_checkout_eventos_doc;
