-- Inventario global de escenario (orquesta) + catálogo de elementos no-instrumento + log de cambios.

-- ---------------------------------------------------------------------------
-- elementos_escenario: props / extras con SVG (mic, etc.) — separado de instrumentos
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.elementos_escenario (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL,
  stage_plot_type text,
  svg_icon text,
  width_cm numeric,
  height_cm numeric,
  activo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT elementos_escenario_stage_plot_type_check
    CHECK (
      stage_plot_type IS NULL
      OR stage_plot_type ~ '^[a-z][a-z0-9_]{0,62}$'
    ),
  CONSTRAINT elementos_escenario_svg_icon_len_check
    CHECK (svg_icon IS NULL OR char_length(svg_icon) <= 100000),
  CONSTRAINT elementos_escenario_width_cm_check
    CHECK (width_cm IS NULL OR (width_cm >= 5 AND width_cm <= 800)),
  CONSTRAINT elementos_escenario_height_cm_check
    CHECK (height_cm IS NULL OR (height_cm >= 5 AND height_cm <= 800))
);

CREATE UNIQUE INDEX IF NOT EXISTS elementos_escenario_stage_plot_type_uidx
  ON public.elementos_escenario (stage_plot_type)
  WHERE stage_plot_type IS NOT NULL;

COMMENT ON TABLE public.elementos_escenario IS
  'Catálogo de elementos de escenario no-instrumento (mic, props) con SVG y tamaño default de insert.';

-- ---------------------------------------------------------------------------
-- inventario_items: stock global (silla/banqueta/atril/tarima/elemento)
-- Tarimas: una fila por dimensión (ancho×profundo×forma).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.inventario_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  categoria text NOT NULL,
  nombre text NOT NULL,
  cantidad integer NOT NULL DEFAULT 0,
  ancho_cm numeric,
  profundo_cm numeric,
  forma text,
  elemento_escenario_id bigint
    REFERENCES public.elementos_escenario(id) ON DELETE SET NULL,
  notas text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT inventario_items_categoria_check
    CHECK (categoria IN ('silla', 'banqueta', 'atril', 'tarima', 'elemento')),
  CONSTRAINT inventario_items_cantidad_check
    CHECK (cantidad >= 0),
  CONSTRAINT inventario_items_forma_check
    CHECK (forma IS NULL OR forma IN ('rect', 'oval')),
  CONSTRAINT inventario_items_tarima_dims_check
    CHECK (
      categoria <> 'tarima'
      OR (
        ancho_cm IS NOT NULL AND profundo_cm IS NOT NULL
        AND ancho_cm >= 10 AND ancho_cm <= 800
        AND profundo_cm >= 10 AND profundo_cm <= 800
        AND forma IS NOT NULL
      )
    ),
  CONSTRAINT inventario_items_elemento_fk_check
    CHECK (
      categoria <> 'elemento'
      OR elemento_escenario_id IS NOT NULL
    )
);

-- Una tarima stock-line por (forma, ancho, profundo)
CREATE UNIQUE INDEX IF NOT EXISTS inventario_items_tarima_dims_uidx
  ON public.inventario_items (forma, ancho_cm, profundo_cm)
  WHERE categoria = 'tarima';

-- Una fila stock por categoría simple (silla/banqueta/atril)
CREATE UNIQUE INDEX IF NOT EXISTS inventario_items_simple_cat_uidx
  ON public.inventario_items (categoria)
  WHERE categoria IN ('silla', 'banqueta', 'atril');

CREATE INDEX IF NOT EXISTS inventario_items_categoria_idx
  ON public.inventario_items (categoria);

CREATE INDEX IF NOT EXISTS inventario_items_elemento_escenario_id_idx
  ON public.inventario_items (elemento_escenario_id)
  WHERE elemento_escenario_id IS NOT NULL;

COMMENT ON TABLE public.inventario_items IS
  'Inventario global de escenario (orquesta). Stock no se descuenta al dibujar; solo advertencia.';

-- ---------------------------------------------------------------------------
-- inventario_log: auditoría de cambios de stock / notas
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.inventario_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inventario_item_id bigint NOT NULL
    REFERENCES public.inventario_items(id) ON DELETE CASCADE,
  user_id bigint,
  created_at timestamptz NOT NULL DEFAULT now(),
  mensaje text,
  cantidad_anterior integer,
  cantidad_nueva integer,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS inventario_log_item_created_idx
  ON public.inventario_log (inventario_item_id, created_at DESC);

CREATE INDEX IF NOT EXISTS inventario_log_created_idx
  ON public.inventario_log (created_at DESC);

COMMENT ON TABLE public.inventario_log IS
  'Log de movimientos/cambios del inventario de escenario (quién, cuándo, delta).';

-- Seed stock base (cantidad 0; el staff edita desde Escenario → Inventario)
INSERT INTO public.inventario_items (categoria, nombre, cantidad)
SELECT v.categoria, v.nombre, 0
FROM (VALUES
  ('silla', 'Sillas'),
  ('banqueta', 'Banquetas'),
  ('atril', 'Atriles')
) AS v(categoria, nombre)
WHERE NOT EXISTS (
  SELECT 1 FROM public.inventario_items i WHERE i.categoria = v.categoria
);

-- RLS (mismo patrón que stage_plots: authenticated/anon staff app)
ALTER TABLE public.elementos_escenario ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventario_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventario_log ENABLE ROW LEVEL SECURITY;

CREATE POLICY elementos_escenario_authenticated_all
  ON public.elementos_escenario FOR ALL TO authenticated
  USING (true) WITH CHECK (true);
CREATE POLICY elementos_escenario_anon_all
  ON public.elementos_escenario FOR ALL TO anon
  USING (true) WITH CHECK (true);

CREATE POLICY inventario_items_authenticated_all
  ON public.inventario_items FOR ALL TO authenticated
  USING (true) WITH CHECK (true);
CREATE POLICY inventario_items_anon_all
  ON public.inventario_items FOR ALL TO anon
  USING (true) WITH CHECK (true);

CREATE POLICY inventario_log_authenticated_all
  ON public.inventario_log FOR ALL TO authenticated
  USING (true) WITH CHECK (true);
CREATE POLICY inventario_log_anon_all
  ON public.inventario_log FOR ALL TO anon
  USING (true) WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.elementos_escenario
  TO authenticated, anon, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.inventario_items
  TO authenticated, anon, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.inventario_log
  TO authenticated, anon, service_role;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated, anon, service_role;
