-- Referencias de material para encargos de arreglo (obra del archivo o enlace externo)
CREATE TABLE IF NOT EXISTS public.arreglos_referencias (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_obra bigint NOT NULL
    REFERENCES public.obras(id) ON DELETE CASCADE,
  titulo text NOT NULL,
  id_obra_referencia bigint
    REFERENCES public.obras(id) ON DELETE SET NULL,
  link text,
  orden smallint NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT arreglos_referencias_titulo_not_blank CHECK (btrim(titulo) <> ''),
  CONSTRAINT arreglos_referencias_has_target CHECK (
    id_obra_referencia IS NOT NULL
    OR (link IS NOT NULL AND btrim(link) <> '')
  )
);

CREATE INDEX IF NOT EXISTS idx_arreglos_referencias_id_obra
  ON public.arreglos_referencias (id_obra, orden, id);

CREATE INDEX IF NOT EXISTS idx_arreglos_referencias_obra_ref
  ON public.arreglos_referencias (id_obra_referencia)
  WHERE id_obra_referencia IS NOT NULL;

COMMENT ON TABLE public.arreglos_referencias IS
  'Material de referencia para un encargo de arreglo: obra existente en archivo y/o enlace (p. ej. Drive).';

COMMENT ON COLUMN public.arreglos_referencias.titulo IS
  'Etiqueta breve que describe la referencia (ej. «Versión LEMA», «Partitura IMSLP»).';

COMMENT ON COLUMN public.arreglos_referencias.id_obra_referencia IS
  'Obra del archivo usada como referencia (opcional si hay link).';

COMMENT ON COLUMN public.arreglos_referencias.link IS
  'URL externa de referencia (opcional si hay id_obra_referencia). Puede complementar el link_drive de la obra referenciada.';
