-- Configs de cuerdas first-class por programa (N configs; asociación opcional a bloques).
-- Contenedores existentes quedan bajo una config "Cuerdas" por gira (bloque_ids={}).

CREATE TABLE IF NOT EXISTS public.seating_cuerdas_configs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_programa bigint NOT NULL
    REFERENCES public.programas(id) ON DELETE CASCADE,
  nombre text NOT NULL DEFAULT 'Cuerdas',
  sort_order integer NOT NULL DEFAULT 0,
  bloque_ids bigint[] NOT NULL DEFAULT '{}'::bigint[],
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.seating_cuerdas_configs IS
  'Configs de disposición de cuerdas por programa. 1 config = aplica a todos los bloques; N configs se asocian vía bloque_ids.';

COMMENT ON COLUMN public.seating_cuerdas_configs.sort_order IS
  'Orden de visualización de configs dentro del programa (0 = primero).';

COMMENT ON COLUMN public.seating_cuerdas_configs.bloque_ids IS
  'IDs de programas_repertorios asociados. Vacío = fallback global / aplica a todos si es la única config.';

CREATE INDEX IF NOT EXISTS seating_cuerdas_configs_id_programa_sort_idx
  ON public.seating_cuerdas_configs (id_programa, sort_order, created_at);

ALTER TABLE public.seating_cuerdas_configs ENABLE ROW LEVEL SECURITY;

CREATE POLICY seating_cuerdas_configs_authenticated_all
  ON public.seating_cuerdas_configs
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY seating_cuerdas_configs_anon_all
  ON public.seating_cuerdas_configs
  FOR ALL
  TO anon
  USING (true)
  WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.seating_cuerdas_configs
  TO authenticated, anon, service_role;

GRANT USAGE, SELECT ON SEQUENCE public.seating_cuerdas_configs_id_seq
  TO authenticated, anon, service_role;

-- Contenedores apuntan a una config
ALTER TABLE public.seating_contenedores
  ADD COLUMN IF NOT EXISTS id_config bigint
    REFERENCES public.seating_cuerdas_configs(id) ON DELETE CASCADE;

-- Backfill: una config "Cuerdas" por programa que ya tenga contenedores
INSERT INTO public.seating_cuerdas_configs (id_programa, nombre, sort_order, bloque_ids)
SELECT DISTINCT sc.id_programa, 'Cuerdas', 0, '{}'::bigint[]
FROM public.seating_contenedores sc
WHERE sc.id_programa IS NOT NULL
  AND NOT EXISTS (
    SELECT 1
    FROM public.seating_cuerdas_configs cfg
    WHERE cfg.id_programa = sc.id_programa
  );

UPDATE public.seating_contenedores sc
SET id_config = cfg.id
FROM public.seating_cuerdas_configs cfg
WHERE sc.id_programa = cfg.id_programa
  AND sc.id_config IS NULL;

-- Programas sin contenedores aún no necesitan fila; al crear la primera se crea la config en app.
-- Contenedores huérfanos (sin programa) no deberían existir; si quedan sin config, se bloquea el NOT NULL.

ALTER TABLE public.seating_contenedores
  ALTER COLUMN id_config SET NOT NULL;

CREATE INDEX IF NOT EXISTS seating_contenedores_id_config_idx
  ON public.seating_contenedores (id_config);

COMMENT ON COLUMN public.seating_contenedores.id_config IS
  'Config de cuerdas a la que pertenece este atril/contenedor.';
