-- Logs de estado de difusión por concierto (evento tipo Concierto)

CREATE TABLE IF NOT EXISTS public.conciertos_difusion_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evento bigint NOT NULL REFERENCES public.eventos(id) ON DELETE CASCADE,
    estado text CHECK (estado IS NULL OR estado IN ('en_proceso', 'listo', 'compartido')),
    observaciones text,
    id_editor bigint REFERENCES public.integrantes(id),
    created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS conciertos_difusion_logs_id_evento_created_at_idx
    ON public.conciertos_difusion_logs (id_evento, created_at DESC);

ALTER TABLE public.conciertos_difusion_logs ENABLE ROW LEVEL SECURITY;

-- Cliente web usa la clave anónima (rol `anon`); sin sesión Supabase Auth.
CREATE POLICY "conciertos_difusion_logs_select_anon"
    ON public.conciertos_difusion_logs
    FOR SELECT TO anon
    USING (true);

CREATE POLICY "conciertos_difusion_logs_insert_anon"
    ON public.conciertos_difusion_logs
    FOR INSERT TO anon
    WITH CHECK (true);

COMMENT ON TABLE public.conciertos_difusion_logs IS 'Historial de estados de difusión por evento concierto (append-only).';
