-- Opciones de obra candidatas para un slot placeholder (N:N)
CREATE TABLE IF NOT EXISTS public.repertorio_obras_placeholder_opciones (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_repertorio_obra bigint NOT NULL
    REFERENCES public.repertorio_obras(id) ON DELETE CASCADE,
  id_obra bigint NOT NULL REFERENCES public.obras(id) ON DELETE CASCADE,
  orden smallint NOT NULL DEFAULT 0,
  notas text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT repertorio_obras_placeholder_opciones_uniq
    UNIQUE (id_repertorio_obra, id_obra)
);

CREATE INDEX IF NOT EXISTS idx_ro_placeholder_opciones_obra
  ON public.repertorio_obras_placeholder_opciones (id_obra);

CREATE INDEX IF NOT EXISTS idx_ro_placeholder_opciones_slot
  ON public.repertorio_obras_placeholder_opciones (id_repertorio_obra, orden);

COMMENT ON TABLE public.repertorio_obras_placeholder_opciones IS
  'Obras candidatas para un slot repertorio_obras sin id_obra. Solo visibles/editables por editores del programa.';

COMMENT ON COLUMN public.repertorio_obras_placeholder_opciones.notas IS
  'Nota interna de curaduría sobre esta opción (no confundir con notas_especificas del slot).';
