-- Completa public.paises con estados que no estaban cargados.
-- No pisa filas existentes (Buenos Aires, doble nacionalidad, Inglaterra/Escocia/Gales, Holanda, Qatar, etc.).

INSERT INTO public.paises (nombre)
VALUES
  ('Afganistán'),
  ('Albania'),
  ('Andorra'),
  ('Angola'),
  ('Antigua y Barbuda'),
  ('Argelia'),
  ('Azerbaiyán'),
  ('Bahamas'),
  ('Bangladés'),
  ('Barbados'),
  ('Baréin'),
  ('Belice'),
  ('Benín'),
  ('Bielorrusia'),
  ('Bosnia y Herzegovina'),
  ('Botsuana'),
  ('Brunéi'),
  ('Burkina Faso'),
  ('Burundi'),
  ('Bután'),
  ('Cabo Verde'),
  ('Camboya'),
  ('Camerún'),
  ('Chad'),
  ('Chipre'),
  ('Ciudad del Vaticano'),
  ('Comoras'),
  ('Costa de Marfil'),
  ('Dominica'),
  ('Eritrea'),
  ('Esuatini'),
  ('Etiopía'),
  ('Filipinas'),
  ('Fiyi'),
  ('Gabón'),
  ('Gambia'),
  ('Georgia'),
  ('Ghana'),
  ('Granada'),
  ('Guinea'),
  ('Guinea-Bisáu'),
  ('Guinea Ecuatorial'),
  ('Haití'),
  ('Indonesia'),
  ('Irak'),
  ('Irán'),
  ('Irlanda del Norte'),
  ('Islas Marshall'),
  ('Islas Salomón'),
  ('Jordania'),
  ('Kazajistán'),
  ('Kenia'),
  ('Kirguistán'),
  ('Kiribati'),
  ('Kosovo'),
  ('Kuwait'),
  ('Laos'),
  ('Lesoto'),
  ('Letonia'),
  ('Líbano'),
  ('Liberia'),
  ('Libia'),
  ('Liechtenstein'),
  ('Lituania'),
  ('Macedonia del Norte'),
  ('Madagascar'),
  ('Malasia'),
  ('Malaui'),
  ('Maldivas'),
  ('Malí'),
  ('Malta'),
  ('Mauricio'),
  ('Mauritania'),
  ('Micronesia'),
  ('Moldavia'),
  ('Mongolia'),
  ('Montenegro'),
  ('Mozambique'),
  ('Myanmar'),
  ('Namibia'),
  ('Nauru'),
  ('Nepal'),
  ('Níger'),
  ('Omán'),
  ('Pakistán'),
  ('Palaos'),
  ('Palestina'),
  ('Papúa Nueva Guinea'),
  ('Reino Unido'),
  ('República Centroafricana'),
  ('República del Congo'),
  ('República Democrática del Congo'),
  ('Ruanda'),
  ('Samoa'),
  ('San Cristóbal y Nieves'),
  ('San Marino'),
  ('San Vicente y las Granadinas'),
  ('Santa Lucía'),
  ('Santo Tomé y Príncipe'),
  ('Senegal'),
  ('Seychelles'),
  ('Sierra Leona'),
  ('Singapur'),
  ('Siria'),
  ('Somalia'),
  ('Sri Lanka'),
  ('Sudán'),
  ('Sudán del Sur'),
  ('Tailandia'),
  ('Taiwán'),
  ('Tanzania'),
  ('Tayikistán'),
  ('Timor Oriental'),
  ('Togo'),
  ('Tonga'),
  ('Túnez'),
  ('Turkmenistán'),
  ('Tuvalu'),
  ('Uganda'),
  ('Uzbekistán'),
  ('Vanuatu'),
  ('Vietnam'),
  ('Yemen'),
  ('Yibuti'),
  ('Zambia'),
  ('Zimbabue')
ON CONFLICT (nombre) DO NOTHING;
