-- Tickets de ajuste menor sobre una obra existente (no crea nueva obra de catálogo)
CREATE TABLE IF NOT EXISTS public.obras_ajustes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_obra bigint NOT NULL
    REFERENCES public.obras(id) ON DELETE CASCADE,
  tipo text NOT NULL DEFAULT 'cambio_menor'
    CHECK (tipo IN ('correccion', 'parte_alternativa', 'cambio_menor')),
  estado text NOT NULL DEFAULT 'pendiente'
    CHECK (estado IN ('pendiente', 'cerrado')),
  origen text NOT NULL DEFAULT 'solicitud_interna'
    CHECK (origen IN ('solicitud_interna', 'carga_propia')),
  id_integrante_arreglador bigint
    REFERENCES public.integrantes(id) ON DELETE SET NULL,
  id_usuario_solicita bigint
    REFERENCES public.integrantes(id) ON DELETE SET NULL,
  fecha_esperada date,
  brief text,
  partes_afectadas text,
  archivos_entregados jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  cerrado_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_obras_ajustes_id_obra
  ON public.obras_ajustes (id_obra, estado, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_obras_ajustes_pendientes
  ON public.obras_ajustes (estado, fecha_esperada)
  WHERE estado = 'pendiente';

CREATE INDEX IF NOT EXISTS idx_obras_ajustes_arreglador
  ON public.obras_ajustes (id_integrante_arreglador)
  WHERE id_integrante_arreglador IS NOT NULL;

COMMENT ON TABLE public.obras_ajustes IS
  'Pedido de ajuste menor (corrección / parte alternativa) sobre una obra Entregado/Oficial; no clona catálogo.';

COMMENT ON COLUMN public.obras_ajustes.archivos_entregados IS
  'Lista JSON de {nombre, url} creados al cerrar la entrega (partes nuevas versionadas).';

ALTER TABLE public.obras_ajustes ENABLE ROW LEVEL SECURITY;

CREATE POLICY obras_ajustes_authenticated_all
  ON public.obras_ajustes
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);
