-- Partes omitidas por programa (no se tocan en esa gira; bajan el Req de auditoría).
CREATE TABLE IF NOT EXISTS public.seating_particellas_omitidas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_programa bigint NOT NULL
    REFERENCES public.programas(id) ON DELETE CASCADE,
  id_obra bigint NOT NULL
    REFERENCES public.obras(id) ON DELETE CASCADE,
  id_particella bigint NOT NULL
    REFERENCES public.obras_particellas(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT seating_particellas_omitidas_programa_particella_uniq
    UNIQUE (id_programa, id_particella)
);

CREATE INDEX IF NOT EXISTS seating_particellas_omitidas_programa_idx
  ON public.seating_particellas_omitidas (id_programa);

CREATE INDEX IF NOT EXISTS seating_particellas_omitidas_programa_obra_idx
  ON public.seating_particellas_omitidas (id_programa, id_obra);

COMMENT ON TABLE public.seating_particellas_omitidas IS
  'Particellas omitidas en seating de un programa: no se asignan ni cuentan en Req de instrumentación.';

ALTER TABLE public.seating_particellas_omitidas ENABLE ROW LEVEL SECURITY;

CREATE POLICY seating_particellas_omitidas_authenticated_all
  ON public.seating_particellas_omitidas
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY seating_particellas_omitidas_anon_all
  ON public.seating_particellas_omitidas
  FOR ALL
  TO anon
  USING (true)
  WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.seating_particellas_omitidas
  TO authenticated, anon, service_role;
GRANT USAGE, SELECT ON SEQUENCE public.seating_particellas_omitidas_id_seq
  TO authenticated, anon, service_role;
